const fs = require('fs');
const h = fs.readFileSync('public/landing/cafe-premium-salento/index.html', 'utf8');
const count = (re) => (h.match(re) || []).length;
console.log('menu-card:', count(/class="menu-card"/g));
console.log('seccion Don Elías unica:', h.includes('Catálogo de Café de Salento — Todas las Fincas'));
console.log('vieja seccion eliminada:', !h.includes('Catálogo Oficial') && !h.includes('Otras Fincas'));
console.log('ItemList JSON-LD items:', count(/"@type":"ListItem"/g));
console.log('Product entries:', count(/"@type":"Product"/g));
console.log('brand tags: don-elias=' + count(/tag-don-elias/g) + ' recuerdo=' + count(/tag-recuerdo/g) + ' ocaso=' + count(/tag-ocaso/g));
console.log('catalogo-grid:', h.includes('catalogo-grid'));
console.log('Ofertas con price:', count(/"@type":"Offer"/g));
console.log('PreOrder:', count(/PreOrder/g), 'InStock:', count(/InStock/g));
console.log('img refs ok: verificar rutas');
const imgs = [...h.matchAll(/src="(\/pautas\/[^"]+)"/g)].map(m => m[1]);
const uniq = [...new Set(imgs)];
console.log('imgs unicas en catalogo:', uniq.length);
let missing = 0;
uniq.forEach(p => { if (!fs.existsSync('public' + p)) { console.log('FALTA:', p); missing++; } });
console.log(missing === 0 ? 'todas las imagenes existen' : 'faltan ' + missing);
